---
- name: Deinstalliere Google Chrome, Thunderbird, Rhythmbox und LibreOffice Writer
  hosts: localhost
  become: yes
  tasks:
    - name: Entferne Google Chrome (stabile Version)
      apt:
        name: google-chrome-stable
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne Google Chrome (alternative Paketnamen)
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - google-chrome
        - chrome
      when: ansible_os_family == "Debian"

    - name: Entferne Thunderbird
      apt:
        name: thunderbird
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne lokale Thunderbird-Konfigurationsdateien
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/home/{{ ansible_user_id }}/.thunderbird"
        - "/home/{{ ansible_user_id }}/.mozilla-thunderbird"
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Entferne Rhythmbox
      apt:
        name: rhythmbox
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne lokale Rhythmbox-Konfigurationsdateien
      file:
        path: "/home/{{ ansible_user_id }}/.config/rhythmbox"
        state: absent
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Entferne LibreOffice Writer
      apt:
        name: libreoffice-writer
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"
