---
- name: Deinstalliere diverse Programme komplett
  hosts: localhost
  become: yes
  tasks:
    - name: Entferne Google Chrome (stabile Version)
      apt:
        name: google-chrome-stable
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne Google Chrome (alternative Paketnamen)
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - google-chrome
        - chrome
      when: ansible_os_family == "Debian"

    - name: Entferne Thunderbird
      apt:
        name: thunderbird
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne lokale Thunderbird-Konfigurationsdateien
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/home/{{ ansible_user_id }}/.thunderbird"
        - "/home/{{ ansible_user_id }}/.mozilla-thunderbird"
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: Entferne Rhythmbox
      apt:
        name: rhythmbox
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne lokale Rhythmbox-Konfigurationsdateien
      file:
        path: "/home/{{ ansible_user_id }}/.config/rhythmbox"
        state: absent
      ignore_errors: yes
      when: ansible_os_family == "Debian"

    - name: LibreOffice komplett deinstallieren (inkl. deutsche Lokalisierung)
      apt:
        name:
          - libreoffice
          - libreoffice-l10n-de
          - libreoffice-help-de
          - libreoffice-calc
          - libreoffice-impress
          - libreoffice-math
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne Mines
      apt:
        name: mines
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne Cheese
      apt:
        name: cheese
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"

    - name: Entferne Mahjongg
      apt:
        name: mahjongg
        state: absent
        purge: yes
      when: ansible_os_family == "Debian"
